### ISSUE TITLE
Some minor changes

### ISSUE THREAD

**Issue by Hanaffi** [BassemMagdi0007/Porefolio#1]
Hello Bassem 😃,
You did an awesome job. I really like it.

I just want to highlight some possible changes:

1. There is a typo in the repo name : `Portfolio` not `Porefolio`
2. Some GIFs take long time which could be a bad user experience especially for those who have low internet speed.

--- 

![zz](https://user-images.githubusercontent.com/35642947/118426196-0eed9680-b6cb-11eb-92f4-3cfc805161b0.png)

**Comment by BassemMagdi0007** [comment]
Hello Mr. Essam :D
Really appreciate your feedback and would gladly try to edit & enhance
those bugs.
The point is it was my first time trying to create a front end page so yet
I don't really know how to optimize the loading speed of the GIFs.
But glad you mentioned it to me.... proud of you :D
